### ISSUE TITLE
Does `zx.hsimplify.zh_simp` preseserve the value of `zx.Graph.to_tensor`?

### ISSUE THREAD

**Issue by mhlr** [Quantomatic/pyzx#76]
I have an graph where
```
t1 = g.to_tensor()
zx.hsimplify.zh_simp(g)
t2 = g.to_tensor()
```
where t1 is not equal to t2. Is this a bug?
If not under what circumstances would this happen?

**Comment by jvdwetering** [comment]
That would definitely be a bug. On which graph do you get this?
Do note that we do know that zh_simp is not yet scalar-accurate. So are the tensors actually different or do they only differ by a phase?

**Comment by mhlr** [comment]
It is complete different. I am attaching a notebook demonstrating the issue
[zh-simplify-bug.ipynb.zip](https://github.com/Quantomatic/pyzx/files/7449760/zh-simplify-bug.ipynb.zip)

**Comment by jvdwetering** [comment]
Thanks for the example, I'll look into it!

**Comment by jvdwetering** [comment]
There was a bug in one of the rewrite rules. I fixed that, but then your diagram didn't simplify fully, so I've added another H-box rewrite rule (that was long overdue), and now your diagram simplifies correctly.

**Comment by mhlr** [comment]
Thanks, John! I am not getting the fix
I did
```
pip install -U git+https://github.com/Quantomatic/pyzx.git
```
in my env and restartarted my notebook kernel, but I still get the same behavior as before

**Comment by mhlr** [comment]
Nevermind. It turns out `pip install -U` is not sufficient to update a git installed package. Need to uninstall and reinslall
